name: "📚 Documentation"

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/documentation.yml'
      - 'docs/**/*'
      - "my_awesome_plugin/**/*.py"
      - "my_awesome_plugin/metadata.txt"
      - 'requirements/documentation.txt'
    tags:
      - "*"

  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/documentation.yml"
      - docs/**/*
      - requirements/documentation.txt

  workflow_dispatch:

  workflow_run:
    workflows:
      - "📦 Package & 🚀 Release"
    types:
      - completed

# Allow one concurrent deployment per branch/pr
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get source code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
          cache: "pip"
          cache-dependency-path: "requirements/documentation.txt"
          python-version: ${{ env.PYTHON_VERSION }}

    - name: Cache Sphinx cache
      uses: actions/cache@v4
      with:
        path: docs/_build/cache
        key: ${{ runner.os }}-sphinx-${{ hashFiles('docs/**/*') }}
        restore-keys: |
          ${{ runner.os }}-sphinx-

    - name: Install dependencies
      run: |
        python -m pip install -U pip setuptools wheel
        python -m pip install -U -r requirements/documentation.txt

    - name: Build doc using Sphinx
      run: sphinx-build -b html -j auto -d docs/_build/cache -q docs docs/_build/html

    - name: Download artifact from build workflow
      if: ${{ env.CONDITION_IS_PUSH || env.CONDITION_IS_WORKFLOW_RUN }}
      uses: dawidd6/action-download-artifact@v9
      with:
        allow_forks: false
        branch: main
        event: push
        github_token: ${{ secrets.GITHUB_TOKEN }}
        if_no_artifact_found: warn
        name: ${{ env.PROJECT_FOLDER }}-latest
        path: docs/_build/html/
        # run_id: ${{ github.event.workflow_run.id }}
        workflow: package_and_release.yml

    - name: Save build doc as artifact
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: documentation
        path: docs/_build/html/*
        retention-days: 30

    - name: Setup Pages
      uses: actions/configure-pages@v5
      if: ${{ env.CONDITION_IS_PUSH || env.CONDITION_IS_WORKFLOW_RUN }}

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      if: ${{ env.CONDITION_IS_PUSH || env.CONDITION_IS_WORKFLOW_RUN }}
      with:
        # Upload entire repository
        path: docs/_build/html/

    - name: Deploy to GitHub Pages
      id: deployment
      if: ${{ env.CONDITION_IS_PUSH || env.CONDITION_IS_WORKFLOW_RUN }}
      uses: actions/deploy-pages@v4
